# Don't require a "Signed-off-by" line for GPG signed commits by project members (eg: applying PR suggestions, squash
# merges, locally configured signing, etc).
#     https://github.com/dcoapp/app#skipping-sign-off-for-organization-members
require:
  members: false
