default_install_hook_types: [pre-commit, pre-merge-commit, pre-push, prepare-commit-msg]
default_stages: [manual, pre-commit, pre-merge-commit]
repos:
  - repo: local
    hooks:
      - id: check-dco-sign-off
        name: check DCO sign-off
        entry: bin/check-dco-signoff.sh
        stages: [prepare-commit-msg]
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: sync-deps
        name: "sync dependencies"
        entry: rye sync
        files: ^(.*/)?(requirements(-dev)?\.lock|pyproject\.toml)$
        language: system
        pass_filenames: false
        require_serial: true
        stages:
          - post-checkout
          - post-merge
          - post-rewrite
          - pre-commit # Run on pre-commit (instead of post-commit) to install/update the tools below.
      - id: lint
        name: "lint"
        entry: rye lint
        language: system
        require_serial: true
        types_or: [python, pyi, jupyter]
      - id: format
        name: "format"
        entry: rye fmt
        language: system
        require_serial: true
        types_or: [python, pyi, jupyter]
