name: CI
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
env:
  COLUMNS: 120
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.12"] # NOTE: Quote to ensure trailing 0s aren't dropped
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PRE_COMMIT_HOME: /tmp/pre-commit-cache
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          rye pin ${{ matrix.python-version }}
          rye sync --all-features --no-lock
      - name: pre-commit
        run: |
          export RUFF_FORMAT=github # Configure ruff to annotate commits
          export SKIP=no-commit-to-branch # This workflow runs on commits to main too
          rye run pre-commit run -a
      - name: pytest
        run: |
          rye run pytest --cov-report='xml:coverage-${{ matrix.os }}-${{ matrix.python-version }}.xml'
      - uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON_VERSION
          fail_ci_if_error: true
          files: coverage-${{ matrix.os }}-${{ matrix.python-version }}.xml
          token: ${{ vars.CODECOV_TOKEN }}

  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v'))
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We need to pull the commit and tag history in order to compute a unique version for
          # non-tagged commits. `fetch-depth: 0` is required even with `fetch-tags: true`:
          # - https://github.com/actions/checkout/issues/1471
          fetch-depth: 0
          fetch-tags: true
      - name: Install rye
        uses: eifinger/setup-rye@v4
      - name: Build distributions
        run: |
          # Set a deterministic build date to embed in the package metadata.
          export SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct HEAD)"
          # When building off an untagged commit, hatch-vcs will include a local version identifier
          # with the short commit sha. This is usually desirable locally, but unfortunately these
          # cannot be uploaded to TestPyPI[1][2].
          #
          # 1: https://github.com/pypa/setuptools_scm/issues/455
          # 2: https://github.com/ofek/hatch-vcs/discussions/12
          echo '[tool.hatch.version.raw-options]' >> pyproject.toml
          echo 'local_scheme = "no-local-version"' >> pyproject.toml

          rye build
      - name: Publish to TestPyPI
        run: |
          rye publish \
            --repository testpypi \
            --repository-url https://test.pypi.org/legacy/ \
            --username '__token__' \
            --token '${{ secrets.TEST_PYPI_TOKEN }}' \
            --yes
      - name: Publish to PyPI
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          rye publish \
            --username '__token__' \
            --token '${{ secrets.PYPI_TOKEN }}' \
            --yes

          # TODO: Fix doc generation - pdocs and portray are not maintained and have various issues.
          #
          # echo "Updating docs in GitHub Pages..."
          # git fetch origin gh-pages # Fetch the gh-pages branch so portray commits on top of existing commits.
          # git branch gh-pages origin/gh-pages
          # portray on_github_pages
