# Modified from: https://github.com/dependabot/fetch-metadata#auto-approving
name: Dependabot auto-approve
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v1
      - uses: actions/checkout@v3
      - name: Approve a PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout "${{ github.event.pull_request.html_url }}"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve
            gh pr merge --auto --rebase
          else
            echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
