# Modified from: https://github.com/dependabot/fetch-metadata#auto-approving
name: Dependabot auto-approve
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v1
      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --rebase "${{ github.event.pull_request.html_url }}"
