name: Weekly Lint repository
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: "Install repolinter"
        run: npm install -g repolinter
      - name: "Run repolinter"
        run: repolinter lint --dryRun -g $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
