name: tests
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: pytest
      run: |
        pytest \
            --cov-report="html:htmlcov-${{ matrix.os }}-${{ matrix.python-version }}/" \
            --html="report-${{ matrix.os }}-${{ matrix.python-version }}.html" \
            --self-contained-html
    - name: Upload test and coverage results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          test-report-${{ matrix.os }}-${{ matrix.python-version }}.html
          coverage-report-${{ matrix.os }}-${{ matrix.python-version }}/*
      if: ${{ always() }}
